disabled_rules:
- trailing_whitespace
- type_name
- identifier_name

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- Pods
- RVS_IPAddress_Tests

file_length:
- 1000 # warning
- 1001 # error

type_body_length:
- 500 # warning
- 501 # error

line_length:
- 200 # warning
- 201 # error

cyclomatic_complexity:
- 10 # warning
- 11 # error
