disabled_rules:
- trailing_whitespace
- type_name
- identifier_name

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- Pods
- RVS_IPAddress_Tests
- Test-Playground.playground
- docs

file_length:
- 1000 # warning
- 1001 # error

function_body_length:
- 45 # warning
- 46 # error

type_body_length:
- 500 # warning
- 501 # error

line_length:
- 220 # warning
- 221 # error

cyclomatic_complexity:
- 10 # warning
- 11 # error
